version: '3'

services:
  db:
    image: postgres:10.9

  web:
    build: .
    command: python drf/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
