# Generated by Django 2.2.3 on 2019-07-08 14:08

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
